package cn.zbw.logistics.pojo;

public class BaseData {
   
    private Long baseId;

 
    private String baseName;

 
    private String baseDesc;

    
    private Long parentId;
    
    private String parentName;
    
    
  
    public String getParentName() {
		return parentName;
	}


	public void setParentName(String parentName) {
		this.parentName = parentName;
	}


	public Long getBaseId() {
        return baseId;
    }

    
    public void setBaseId(Long baseId) {
        this.baseId = baseId;
    }

    
    public String getBaseName() {
        return baseName;
    }

   
    public void setBaseName(String baseName) {
        this.baseName = baseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_data.base_desc
     *
     * @return the value of t_base_data.base_desc
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    public String getBaseDesc() {
        return baseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_data.base_desc
     *
     * @param baseDesc the value for t_base_data.base_desc
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    public void setBaseDesc(String baseDesc) {
        this.baseDesc = baseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_data.parent_id
     *
     * @return the value of t_base_data.parent_id
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_data.parent_id
     *
     * @param parentId the value for t_base_data.parent_id
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}