package cn.zbw.logistics.pojo;

public class Customer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.customer_id
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private Long customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.customer_name
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private String customerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.phone
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.email
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.address
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.gender
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.remark
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.id_card
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private String idCard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.user_id
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.base_id
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private Long baseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.realname
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_customer.base_name
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	private String baseName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.customer_id
	 * @return  the value of v_customer.customer_id
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public Long getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.customer_id
	 * @param customerId  the value for v_customer.customer_id
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.customer_name
	 * @return  the value of v_customer.customer_name
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public String getCustomerName() {
		return customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.customer_name
	 * @param customerName  the value for v_customer.customer_name
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.phone
	 * @return  the value of v_customer.phone
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.phone
	 * @param phone  the value for v_customer.phone
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.email
	 * @return  the value of v_customer.email
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.email
	 * @param email  the value for v_customer.email
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.address
	 * @return  the value of v_customer.address
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.address
	 * @param address  the value for v_customer.address
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.gender
	 * @return  the value of v_customer.gender
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.gender
	 * @param gender  the value for v_customer.gender
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.remark
	 * @return  the value of v_customer.remark
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.remark
	 * @param remark  the value for v_customer.remark
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.id_card
	 * @return  the value of v_customer.id_card
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public String getIdCard() {
		return idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.id_card
	 * @param idCard  the value for v_customer.id_card
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.user_id
	 * @return  the value of v_customer.user_id
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.user_id
	 * @param userId  the value for v_customer.user_id
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.base_id
	 * @return  the value of v_customer.base_id
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public Long getBaseId() {
		return baseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.base_id
	 * @param baseId  the value for v_customer.base_id
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setBaseId(Long baseId) {
		this.baseId = baseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.realname
	 * @return  the value of v_customer.realname
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.realname
	 * @param realname  the value for v_customer.realname
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_customer.base_name
	 * @return  the value of v_customer.base_name
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public String getBaseName() {
		return baseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_customer.base_name
	 * @param baseName  the value for v_customer.base_name
	 * @mbg.generated  Thu Oct 10 19:44:50 CST 2019
	 */
	public void setBaseName(String baseName) {
		this.baseName = baseName;
	}
}