package cn.zbw.logistics.pojo;

import java.util.List;

public class Order {
    
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    private Long userId;
    private List<OrderDetail> orderDetails;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.customer_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shipping_address
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    private String shippingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shipping_name
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    private String shippingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shipping_phone
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    private String shippingPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.take_name
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    private String takeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.take_address
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    private String takeAddress;


    private String takePhone;


    private Integer orderStatus;


    private Long paymentMethodId;


    private Long intervalId;


    private Long takeMethodId;
    
    private String realname;
    
    private String customerName;

    private Long freightMethodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_remark
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    private String orderRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    
    
    public Long getOrderId() {
        return orderId;
    }

    public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public Long getUserId() {
        return userId;
    }
    
    
    
    public List<OrderDetail> getOrderDetails() {
		return orderDetails;
	}

	public void setOrderDetails(List<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.customer_id
     *
     * @return the value of t_order.customer_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.customer_id
     *
     * @param customerId the value for t_order.customer_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shipping_address
     *
     * @return the value of t_order.shipping_address
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public String getShippingAddress() {
        return shippingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shipping_address
     *
     * @param shippingAddress the value for t_order.shipping_address
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shipping_name
     *
     * @return the value of t_order.shipping_name
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public String getShippingName() {
        return shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shipping_name
     *
     * @param shippingName the value for t_order.shipping_name
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setShippingName(String shippingName) {
        this.shippingName = shippingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shipping_phone
     *
     * @return the value of t_order.shipping_phone
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public String getShippingPhone() {
        return shippingPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shipping_phone
     *
     * @param shippingPhone the value for t_order.shipping_phone
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setShippingPhone(String shippingPhone) {
        this.shippingPhone = shippingPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.take_name
     *
     * @return the value of t_order.take_name
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public String getTakeName() {
        return takeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.take_name
     *
     * @param takeName the value for t_order.take_name
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setTakeName(String takeName) {
        this.takeName = takeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.take_address
     *
     * @return the value of t_order.take_address
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public String getTakeAddress() {
        return takeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.take_address
     *
     * @param takeAddress the value for t_order.take_address
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setTakeAddress(String takeAddress) {
        this.takeAddress = takeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.take_phone
     *
     * @return the value of t_order.take_phone
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public String getTakePhone() {
        return takePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.take_phone
     *
     * @param takePhone the value for t_order.take_phone
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setTakePhone(String takePhone) {
        this.takePhone = takePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_status
     *
     * @return the value of t_order.order_status
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_status
     *
     * @param orderStatus the value for t_order.order_status
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.payment_method_id
     *
     * @return the value of t_order.payment_method_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public Long getPaymentMethodId() {
        return paymentMethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.payment_method_id
     *
     * @param paymentMethodId the value for t_order.payment_method_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setPaymentMethodId(Long paymentMethodId) {
        this.paymentMethodId = paymentMethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.interval_id
     *
     * @return the value of t_order.interval_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public Long getIntervalId() {
        return intervalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.interval_id
     *
     * @param intervalId the value for t_order.interval_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setIntervalId(Long intervalId) {
        this.intervalId = intervalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.take_method_id
     *
     * @return the value of t_order.take_method_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public Long getTakeMethodId() {
        return takeMethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.take_method_id
     *
     * @param takeMethodId the value for t_order.take_method_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setTakeMethodId(Long takeMethodId) {
        this.takeMethodId = takeMethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.freight_method_id
     *
     * @return the value of t_order.freight_method_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public Long getFreightMethodId() {
        return freightMethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.freight_method_id
     *
     * @param freightMethodId the value for t_order.freight_method_id
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setFreightMethodId(Long freightMethodId) {
        this.freightMethodId = freightMethodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_remark
     *
     * @return the value of t_order.order_remark
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_remark
     *
     * @param orderRemark the value for t_order.order_remark
     *
     * @mbg.generated Sat Oct 12 17:49:48 CST 2019
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark;
    }

	@Override
	public String toString() {
		return "Order [orderId=" + orderId + ", userId=" + userId + ", orderDetails=" + orderDetails + ", customerId="
				+ customerId + ", shippingAddress=" + shippingAddress + ", shippingName=" + shippingName
				+ ", shippingPhone=" + shippingPhone + ", takeName=" + takeName + ", takeAddress=" + takeAddress
				+ ", takePhone=" + takePhone + ", orderStatus=" + orderStatus + ", paymentMethodId=" + paymentMethodId
				+ ", intervalId=" + intervalId + ", takeMethodId=" + takeMethodId + ", realname=" + realname
				+ ", customerName=" + customerName + ", freightMethodId=" + freightMethodId + ", orderRemark="
				+ orderRemark + "]";
	}
    
}