package cn.zbw.logistics.pojo;

import java.math.BigDecimal;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.order_detail_id
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Long orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.order_id
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_name
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_number
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Integer goodsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_unit
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Long goodsUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_unit_price
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Long goodsUnitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_total
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Long goodsTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_remark
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private String goodsRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_width
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Double goodsWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_volume
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Double goodsVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_heavy
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Double goodsHeavy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.good_delivery_price
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private BigDecimal goodDeliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.good_length
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Double goodLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.good_height
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    private Double goodHeight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.order_detail_id
     *
     * @return the value of t_order_detail.order_detail_id
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Long getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.order_detail_id
     *
     * @param orderDetailId the value for t_order_detail.order_detail_id
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setOrderDetailId(Long orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.order_id
     *
     * @return the value of t_order_detail.order_id
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.order_id
     *
     * @param orderId the value for t_order_detail.order_id
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_name
     *
     * @return the value of t_order_detail.goods_name
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_name
     *
     * @param goodsName the value for t_order_detail.goods_name
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_number
     *
     * @return the value of t_order_detail.goods_number
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Integer getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_number
     *
     * @param goodsNumber the value for t_order_detail.goods_number
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodsNumber(Integer goodsNumber) {
        this.goodsNumber = goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_unit
     *
     * @return the value of t_order_detail.goods_unit
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Long getGoodsUnit() {
        return goodsUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_unit
     *
     * @param goodsUnit the value for t_order_detail.goods_unit
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodsUnit(Long goodsUnit) {
        this.goodsUnit = goodsUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_unit_price
     *
     * @return the value of t_order_detail.goods_unit_price
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Long getGoodsUnitPrice() {
        return goodsUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_unit_price
     *
     * @param goodsUnitPrice the value for t_order_detail.goods_unit_price
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodsUnitPrice(Long goodsUnitPrice) {
        this.goodsUnitPrice = goodsUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_total
     *
     * @return the value of t_order_detail.goods_total
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Long getGoodsTotal() {
        return goodsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_total
     *
     * @param goodsTotal the value for t_order_detail.goods_total
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodsTotal(Long goodsTotal) {
        this.goodsTotal = goodsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_remark
     *
     * @return the value of t_order_detail.goods_remark
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public String getGoodsRemark() {
        return goodsRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_remark
     *
     * @param goodsRemark the value for t_order_detail.goods_remark
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodsRemark(String goodsRemark) {
        this.goodsRemark = goodsRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_width
     *
     * @return the value of t_order_detail.goods_width
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Double getGoodsWidth() {
        return goodsWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_width
     *
     * @param goodsWidth the value for t_order_detail.goods_width
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodsWidth(Double goodsWidth) {
        this.goodsWidth = goodsWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_volume
     *
     * @return the value of t_order_detail.goods_volume
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Double getGoodsVolume() {
        return goodsVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_volume
     *
     * @param goodsVolume the value for t_order_detail.goods_volume
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodsVolume(Double goodsVolume) {
        this.goodsVolume = goodsVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_heavy
     *
     * @return the value of t_order_detail.goods_heavy
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Double getGoodsHeavy() {
        return goodsHeavy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_heavy
     *
     * @param goodsHeavy the value for t_order_detail.goods_heavy
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodsHeavy(Double goodsHeavy) {
        this.goodsHeavy = goodsHeavy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.good_delivery_price
     *
     * @return the value of t_order_detail.good_delivery_price
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public BigDecimal getGoodDeliveryPrice() {
        return goodDeliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.good_delivery_price
     *
     * @param goodDeliveryPrice the value for t_order_detail.good_delivery_price
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodDeliveryPrice(BigDecimal goodDeliveryPrice) {
        this.goodDeliveryPrice = goodDeliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.good_length
     *
     * @return the value of t_order_detail.good_length
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Double getGoodLength() {
        return goodLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.good_length
     *
     * @param goodLength the value for t_order_detail.good_length
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodLength(Double goodLength) {
        this.goodLength = goodLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.good_height
     *
     * @return the value of t_order_detail.good_height
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public Double getGoodHeight() {
        return goodHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.good_height
     *
     * @param goodHeight the value for t_order_detail.good_height
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    public void setGoodHeight(Double goodHeight) {
        this.goodHeight = goodHeight;
    }

	@Override
	public String toString() {
		return "OrderDetail [orderDetailId=" + orderDetailId + ", orderId=" + orderId + ", goodsName=" + goodsName
				+ ", goodsNumber=" + goodsNumber + ", goodsUnit=" + goodsUnit + ", goodsUnitPrice=" + goodsUnitPrice
				+ ", goodsTotal=" + goodsTotal + ", goodsRemark=" + goodsRemark + ", goodsWidth=" + goodsWidth
				+ ", goodsVolume=" + goodsVolume + ", goodsHeavy=" + goodsHeavy + ", goodDeliveryPrice="
				+ goodDeliveryPrice + ", goodLength=" + goodLength + ", goodHeight=" + goodHeight + "]";
	}
    
}