package cn.zbw.logistics.mapper;

import cn.zbw.logistics.pojo.BaseData;
import cn.zbw.logistics.pojo.BaseDataExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BaseDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_data
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    int deleteByPrimaryKey(Long baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_data
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    int insert(BaseData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_data
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    int insertSelective(BaseData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_data
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    List<BaseData> selectByExample(BaseDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_data
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    BaseData selectByPrimaryKey(Long baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_data
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    int updateByPrimaryKeySelective(BaseData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_data
     *
     * @mbg.generated Mon Oct 07 16:59:31 CST 2019
     */
    int updateByPrimaryKey(BaseData record);
    
    List<BaseData> selecBaseDatasByParentName(@Param("parentName") String parentName);
}