package cn.zbw.logistics.mapper;

import cn.zbw.logistics.pojo.OrderDetail;
import cn.zbw.logistics.pojo.OrderDetailExample;
import java.util.List;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    int deleteByPrimaryKey(Long orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    OrderDetail selectByPrimaryKey(Long orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbg.generated Tue Oct 15 21:52:23 CST 2019
     */
    int updateByPrimaryKey(OrderDetail record);
}